### ISSUE TITLE
Problem: After some time idle, zlistx assertion failure

### ISSUE THREAD

**Issue by jemc** [edgenet/hydra#69]
After some time of being idle (no new posts crossing back and forth between hydras), I see a zlistx assertion failure, often at the same time on both hydras.

Here is the backtrace for all threads given by gdb:

```
[...]
W: 15-01-28 01:49:44 hydra_ledger: store post, ident=3ED52811BADAD955626F691EFF6A493D3EC4701B
W: 15-01-28 01:49:44 hydra_ledger: store post, ident=6073F47541E7A7FAF79A3383126842F322FF38AC
W: 15-01-28 01:49:44 hydra_ledger: store post, ident=EC6CB4F4ABB06EB3027BDC826E135E4CFC5A5343
W: 15-01-28 01:49:44 hydra_ledger: store post, ident=A5ACC41151AA0C88E7F711C390E48D202EB2D14A
W: 15-01-28 01:49:44 hydra_ledger: store post, ident=51571C4BF60759E4780E5870F70EDD1C36FFC27C
W: 15-01-28 01:49:44 hydra_ledger: store post, ident=C284FC29F5A2742F1F310C90A20DAFF580FE0092
W: 15-01-28 01:49:44 hydra_ledger: store post, ident=993998CA98722B45395694E59BDF0FF8FF19F574
W: 15-01-28 01:49:44 hydra_ledger: store post, ident=BCBE761DF7DE6665CDBCD91898C6CFC31D877A61
W: 15-01-28 01:49:44 hydra_ledger: store post, ident=F70AEAD5C538726ADA4C02C2C8B7B029C0A3FAEF
W: 15-01-28 01:49:44 hydra_ledger: store post, ident=87AF476DCCBC9E064AA699C2BDF6C2B7469ED019
hydrad: src/zlistx.c:351: zlistx_detach: Assertion `node->tag == 0x0006cafe' failed.

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff5693700 (LWP 18930)]
0x0000003f34e35877 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.18-16.fc20.x86_64 libgcc-4.8.3-7.fc20.x86_64 libstdc++-4.8.3-7.fc20.x86_64 libuuid-2.24.2-1.fc20.x86_64
(gdb) thread apply all bt

Thread 9 (Thread 0x7fffdf7fe700 (LWP 19266)):
#0  0x0000003f34eea71d in poll () from /lib64/libc.so.6
#1  0x00007ffff76e7c3d in zmq_poll (items_=0x7fffd4002700, nitems_=3, timeout_=timeout_@entry=3600000)
    at src/zmq.cpp:746
#2  0x00007ffff79289b7 in zloop_start (self=0x7fffd40019b0) at src/zloop.c:731
#3  0x00007ffff7dce3ba in hydra_client (cmdpipe=0x7ffff0028fe0, msgpipe=0x7ffff00217a0)
    at ./src/hydra_client_engine.inc:1314
#4  0x00007ffff7912e53 in s_thread_shim (args=0x7ffff0028fc0) at src/zactor.c:67
#5  0x0000003f35207ee5 in start_thread () from /lib64/libpthread.so.0
#6  0x0000003f34ef4b8d in clone () from /lib64/libc.so.6

Thread 8 (Thread 0x7fffdffff700 (LWP 19057)):
#0  0x0000003f34eea71d in poll () from /lib64/libc.so.6
#1  0x00007ffff76e7c3d in zmq_poll (items_=0x7fffd8002700, nitems_=3, timeout_=timeout_@entry=3600000)
    at src/zmq.cpp:746
#2  0x00007ffff79289b7 in zloop_start (self=0x7fffd80019b0) at src/zloop.c:731
#3  0x00007ffff7dce3ba in hydra_client (cmdpipe=0x7ffff001a010, msgpipe=0x7ffff0018790)
    at ./src/hydra_client_engine.inc:1314
#4  0x00007ffff7912e53 in s_thread_shim (args=0x7ffff0019ff0) at src/zactor.c:67
#5  0x0000003f35207ee5 in start_thread () from /lib64/libpthread.so.0
#6  0x0000003f34ef4b8d in clone () from /lib64/libc.so.6

---Type <return> to continue, or q <return> to quit---
Thread 7 (Thread 0x7ffff4c66700 (LWP 18931)):
#0  0x0000003f34eea71d in poll () from /lib64/libc.so.6
#1  0x00007ffff76e7c3d in zmq_poll (items_=items_@entry=0x7ffff4c65e30, nitems_=2, timeout_=1000) at src/zmq.cpp:746
#2  0x00007ffff791790d in zbeacon (pipe=<optimized out>, args=<optimized out>) at src/zbeacon.c:294
#3  0x00007ffff7912e53 in s_thread_shim (args=0x7fffe8003670) at src/zactor.c:67
#4  0x0000003f35207ee5 in start_thread () from /lib64/libpthread.so.0
#5  0x0000003f34ef4b8d in clone () from /lib64/libc.so.6

Thread 6 (Thread 0x7ffff5693700 (LWP 18930)):
#0  0x0000003f34e35877 in raise () from /lib64/libc.so.6
#1  0x0000003f34e36f68 in abort () from /lib64/libc.so.6
#2  0x0000003f34e2e7d6 in __assert_fail_base () from /lib64/libc.so.6
#3  0x0000003f34e2e882 in __assert_fail () from /lib64/libc.so.6
#4  0x00007ffff79266b3 in zlistx_detach (self=self@entry=0x7fffec0024e0, handle=<optimized out>) at src/zlistx.c:351
#5  0x00007ffff79266f2 in zlistx_delete (self=0x7fffec0024e0, handle=<optimized out>) at src/zlistx.c:377
#6  0x00007ffff7928aad in zloop_start (self=0x7fffec0022b0) at src/zloop.c:765
#7  0x00007ffff7dcb08a in hydra_server (pipe=0x7ffff00096b0, args=0x0) at ./src/hydra_server_engine.inc:1027
#8  0x00007ffff7912e53 in s_thread_shim (args=0x7ffff00096f0) at src/zactor.c:67
#9  0x0000003f35207ee5 in start_thread () from /lib64/libpthread.so.0
#10 0x0000003f34ef4b8d in clone () from /lib64/libc.so.6

Thread 5 (Thread 0x7ffff5e94700 (LWP 18929)):
#0  0x0000003f34eea71d in poll () from /lib64/libc.so.6
---Type <return> to continue, or q <return> to quit---
#1  0x00007ffff76e7c3d in zmq_poll (items_=0x7fffe8005060, nitems_=3, timeout_=timeout_@entry=1000) at src/zmq.cpp:746
#2  0x00007ffff792ce88 in zpoller_wait (self=0x7fffe80011b0, timeout=1000) at src/zpoller.c:145
#3  0x00007ffff7bab721 in zyre_node_actor (pipe=<optimized out>, args=<optimized out>) at src/zyre_node.c:851
#4  0x00007ffff7912e53 in s_thread_shim (args=0x7ffff00019c0) at src/zactor.c:67
#5  0x0000003f35207ee5 in start_thread () from /lib64/libpthread.so.0
#6  0x0000003f34ef4b8d in clone () from /lib64/libc.so.6

Thread 4 (Thread 0x7ffff6695700 (LWP 18928)):
#0  0x0000003f34eea71d in poll () from /lib64/libc.so.6
#1  0x00007ffff76d0d4a in zmq::signaler_t::wait (this=this@entry=0x7ffff00213e0, timeout_=timeout_@entry=-1)
    at src/signaler.cpp:205
#2  0x00007ffff76bd080 in zmq::mailbox_t::recv (this=this@entry=0x7ffff0021380, cmd_=cmd_@entry=0x7ffff6694a70, 
    timeout_=-1) at src/mailbox.cpp:70
#3  0x00007ffff76d1e36 in zmq::socket_base_t::process_commands (this=this@entry=0x7ffff0020fc0, 
    timeout_=<optimized out>, throttle_=throttle_@entry=false) at src/socket_base.cpp:980
#4  0x00007ffff76d24fb in zmq::socket_base_t::recv (this=this@entry=0x7ffff0020fc0, msg_=msg_@entry=0x7ffff6694b00, 
    flags_=flags_@entry=0) at src/socket_base.cpp:912
#5  0x00007ffff76e7519 in s_recvmsg (s_=s_@entry=0x7ffff0020fc0, msg_=msg_@entry=0x7ffff6694b00, 
    flags_=flags_@entry=0) at src/zmq.cpp:446
#6  0x00007ffff76e771a in zmq_msg_recv (msg_=msg_@entry=0x7ffff6694b00, s_=s_@entry=0x7ffff0020fc0, 
    flags_=flags_@entry=0) at src/zmq.cpp:590
#7  0x00007ffff76e772e in zmq_recvmsg (s_=s_@entry=0x7ffff0020fc0, msg_=msg_@entry=0x7ffff6694b00, 
    flags_=flags_@entry=0) at src/zmq.cpp:455
---Type <return> to continue, or q <return> to quit---
#8  0x00007ffff7939b1d in zstr_recv (source=<optimized out>) at src/zstr.c:67
#9  0x00007ffff7dcf373 in s_accept_reply (self=0x7ffff0011300) at ./src/hydra_client_engine.inc:1435
#10 0x00007ffff7dcf063 in hydra_client_destructor (self=0x7ffff0011300) at ./src/hydra_client_engine.inc:1500
#11 0x00007ffff7dcef6d in hydra_client_destroy (self_p=0x7ffff6694e08) at ./src/hydra_client_engine.inc:1385
#12 0x00007ffff7dc58b1 in s_self_handle_zyre (self=0x7ffff00008c0) at src/hydra.c:493
#13 0x00007ffff7dc4c7b in s_self_actor (pipe=0x603070, args=0x401312) at src/hydra.c:540
#14 0x00007ffff7912e53 in s_thread_shim (args=0x603050) at src/zactor.c:67
#15 0x0000003f35207ee5 in start_thread () from /lib64/libpthread.so.0
#16 0x0000003f34ef4b8d in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x7ffff6e96700 (LWP 18927)):
#0  0x0000003f34ef5163 in epoll_wait () from /lib64/libc.so.6
#1  0x00007ffff76b94b6 in zmq::epoll_t::loop (this=0x605bc0) at src/epoll.cpp:146
#2  0x00007ffff76e1e80 in thread_routine (arg_=0x605c40) at src/thread.cpp:86
#3  0x0000003f35207ee5 in start_thread () from /lib64/libpthread.so.0
#4  0x0000003f34ef4b8d in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x7ffff7697700 (LWP 18926)):
#0  0x0000003f34ef5163 in epoll_wait () from /lib64/libc.so.6
#1  0x00007ffff76b94b6 in zmq::epoll_t::loop (this=0x605740) at src/epoll.cpp:146
#2  0x00007ffff76e1e80 in thread_routine (arg_=0x6057c0) at src/thread.cpp:86
#3  0x0000003f35207ee5 in start_thread () from /lib64/libpthread.so.0
#4  0x0000003f34ef4b8d in clone () from /lib64/libc.so.6
---Type <return> to continue, or q <return> to quit---

Thread 1 (Thread 0x7ffff76997c0 (LWP 18921)):
#0  0x0000003f34ebc6ed in nanosleep () from /lib64/libc.so.6
#1  0x0000003f34ebc584 in sleep () from /lib64/libc.so.6
#2  0x0000000000401099 in main (argc=1, argv=0x7fffffffddc8) at src/hydrad.c:102
(gdb)
```

**Comment by hintjens** [comment]
OK, this is something tripping up in the ticket management, which was code
I optimized some time ago in zloop. I've managed to reproduce on Linux, so
am now investigating.

On Wed, Jan 28, 2015 at 10:53 AM, Joe Eli McIlvain <notifications@github.com

**Comment by hintjens** [comment]
Fixed in CZMQ: https://github.com/zeromq/czmq/pull/904
